//
// TourRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TourRequest: Codable, JSONEncodable, Hashable {

    public var title: String
    public var source: String?
    public var multimediaObjects: [String]
    public var author: String?
    public var tags: [String]?

    public init(title: String, source: String? = nil, multimediaObjects: [String], author: String? = nil, tags: [String]? = nil) {
        self.title = title
        self.source = source
        self.multimediaObjects = multimediaObjects
        self.author = author
        self.tags = tags
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case title
        case source
        case multimediaObjects
        case author
        case tags
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(title, forKey: .title)
        try container.encodeIfPresent(source, forKey: .source)
        try container.encode(multimediaObjects, forKey: .multimediaObjects)
        try container.encodeIfPresent(author, forKey: .author)
        try container.encodeIfPresent(tags, forKey: .tags)
    }
}

