//
// UserResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UserResponse: Codable, JSONEncodable, Hashable {

    public var id: String?
    public var email: String?
    public var password: String?
    public var lastLogin: String?
    public var activeSessions: [UserSessionResponse]?
    public var role: String?

    public init(id: String? = nil, email: String? = nil, password: String? = nil, lastLogin: String? = nil, activeSessions: [UserSessionResponse]? = nil, role: String? = nil) {
        self.id = id
        self.email = email
        self.password = password
        self.lastLogin = lastLogin
        self.activeSessions = activeSessions
        self.role = role
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case email
        case password
        case lastLogin
        case activeSessions
        case role
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encodeIfPresent(password, forKey: .password)
        try container.encodeIfPresent(lastLogin, forKey: .lastLogin)
        try container.encodeIfPresent(activeSessions, forKey: .activeSessions)
        try container.encodeIfPresent(role, forKey: .role)
    }
}

